# Generated by Django 5.0.4 on 2024-04-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
